name: Termux sdk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#working-directory
jobs:
  
  clone:
    runs-on: ubuntu-latest
    name: clone repo
    steps:
    - name: clone
      env:
        GITHUB_REPO: https://github.com/Lzhiyong/termux-ndk/releases/download/android-sdk/android-sdk.tar.xz
      run: |
        wget $GITHUB_REPO
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: android-sdk
        release_name: Release android-sdk
        body: |
          android-sdk aarch64
        draft: false
        prerelease: false

    
    