name: Termux sdk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#working-directory
jobs:
  
  clone:
    runs-on: ubuntu-latest
    name: clone repo
    steps:
    - name: clone
      env:
        GITHUB_REPO: https://github.com/Lzhiyong/termux-ndk/releases/download/android-sdk/android-sdk.tar.xz
      run: |
        wget $GITHUB_REPO
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: android-sdk
        release_name: Release android-sdk
        body: |
          android-sdk aarch64
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./android-sdk.tar.xz
        asset_name: android-sdk.tar.xz
        asset_content_type: application/tar.xz

    
    